# Generated by Django 5.1.6 on 2025-02-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_add_insurance_insurance_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_insurance',
            name='reminder_date',
            field=models.DateField(default='2001-10-10'),
            preserve_default=False,
        ),
    ]
