# Generated by Django 5.1.6 on 2025-02-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_add_insurance_reminder_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('registreation_no', models.CharField(max_length=50)),
                ('vehicle_model', models.DateField()),
                ('manufacturing_year', models.DateField()),
                ('previous_policy_no', models.IntegerField()),
                ('insurance_name', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
