# Generated by Django 5.1.6 on 2025-02-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_registreation_no_add_enquiry_registration_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_enquiry',
            name='expiry_date',
            field=models.DateField(default='2000-10-20'),
            preserve_default=False,
        ),
    ]
