# Generated by Django 5.1.6 on 2025-02-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_add_enquiry_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_gps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50)),
                ('vehicle_registration_no', models.IntegerField()),
                ('vehicle_model', models.DateField()),
                ('vehicle_make', models.DateField()),
                ('vehicle_type', models.CharField(max_length=50)),
            ],
        ),
    ]
