# Generated by Django 5.1.6 on 2025-03-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_add_gps'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('insurance_id', models.IntegerField()),
                ('vehicle_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('vehicle_type', models.CharField(max_length=50)),
                ('policy_type', models.CharField(max_length=50)),
                ('policy_amount', models.IntegerField()),
                ('insurance_start_date', models.DateField()),
                ('insurance_end_date', models.DateField()),
                ('reminder_date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='add_insurance',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='add_insurance',
            old_name='insurance_end_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='add_insurance',
            old_name='address',
            new_name='insurance_name',
        ),
        migrations.RenameField(
            model_name='add_insurance',
            old_name='insurance_id',
            new_name='policy_no',
        ),
        migrations.RenameField(
            model_name='add_insurance',
            old_name='email',
            new_name='registration_no',
        ),
        migrations.RenameField(
            model_name='add_insurance',
            old_name='insurance_start_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='add_insurance',
            old_name='reminder_date',
            new_name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='add_insurance',
            name='policy_amount',
        ),
        migrations.RemoveField(
            model_name='add_insurance',
            name='policy_type',
        ),
        migrations.RemoveField(
            model_name='add_insurance',
            name='vehicle_no',
        ),
        migrations.AddField(
            model_name='add_insurance',
            name='year',
            field=models.DateField(default='2000-12-12'),
            preserve_default=False,
        ),
    ]
