# Generated by Django 5.1.6 on 2025-03-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_add_customer_rename_date_add_insurance_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_insurance',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
