# Generated by Django 5.1.7 on 2025-03-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_add_insurance_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='pavan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField(max_length=20)),
            ],
        ),
    ]
