# Generated by Django 5.1.6 on 2025-03-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_add_gps_vehicle_id_add_gps_gps_device_imei_n0_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_gps',
            old_name='reminder_date',
            new_name='reminder_dates',
        ),
    ]
