# Generated by Django 5.1.7 on 2025-03-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_pavan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pavan',
        ),
    ]
