# Generated by Django 5.1.6 on 2025-03-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_rename_reminder_date_add_gps_reminder_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_gps',
            name='renew_date',
        ),
    ]
