# Generated by Django 5.1.7 on 2025-03-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_delete_pavan'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(max_length=20)),
                ('cust_name', models.CharField(max_length=30)),
                ('email_id', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='customer_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(max_length=20)),
                ('cust_name', models.CharField(max_length=30)),
                ('phone_no', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='add_customer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='add_customer',
            name='insurance_end_date',
        ),
        migrations.RemoveField(
            model_name='add_customer',
            name='insurance_id',
        ),
        migrations.RemoveField(
            model_name='add_customer',
            name='insurance_start_date',
        ),
        migrations.RemoveField(
            model_name='add_customer',
            name='policy_amount',
        ),
        migrations.RemoveField(
            model_name='add_customer',
            name='policy_type',
        ),
        migrations.RemoveField(
            model_name='add_customer',
            name='reminder_date',
        ),
        migrations.RemoveField(
            model_name='add_customer',
            name='vehicle_no',
        ),
        migrations.RemoveField(
            model_name='add_customer',
            name='vehicle_type',
        ),
        migrations.AlterField(
            model_name='add_customer',
            name='phone',
            field=models.IntegerField(default=9392947372),
            preserve_default=False,
        ),
    ]
