# Generated by Django 5.1.6 on 2025-03-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_add_gps_renew_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_gps',
            name='Gps_device_IMEI_n0',
        ),
        migrations.RemoveField(
            model_name='add_gps',
            name='install_date',
        ),
        migrations.RemoveField(
            model_name='add_gps',
            name='reminder_dates',
        ),
        migrations.RemoveField(
            model_name='add_gps',
            name='vehicle_registration_no',
        ),
    ]
