# Generated by Django 5.1.7 on 2025-03-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_customer_details_customer_master_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_customer',
        ),
        migrations.RenameField(
            model_name='customer_details',
            old_name='cust_id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='customer_details',
            old_name='cust_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='customer_master',
            old_name='cust_id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='customer_master',
            old_name='cust_name',
            new_name='customer_name',
        ),
        migrations.AddField(
            model_name='customer_details',
            name='phone',
            field=models.IntegerField(default=9392584900),
            preserve_default=False,
        ),
    ]
