# Generated by Django 5.1.7 on 2025-03-11 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_delete_add_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_master',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
