# Generated by Django 5.1.7 on 2025-03-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_rename_phone_no_customer_master_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_gps',
            name='gps_id',
            field=models.CharField(default=939265900, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='add_gps',
            name='vehicle_registration_no',
            field=models.CharField(max_length=20),
        ),
    ]
