# Generated by Django 5.1.6 on 2025-03-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_add_gps_gps_device_imei_no_add_gps_install_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_gps',
            name='vehicle_registration_no',
        ),
    ]
