# Generated by Django 5.1.7 on 2025-03-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_add_gps_gps_id_alter_add_gps_vehicle_registration_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_gps',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='add_gps',
            name='customer_name',
            field=models.CharField(default=8754224577, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_gps',
            name='imei_no',
            field=models.IntegerField(default=9392584900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_gps',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
