# Generated by Django 5.1.6 on 2025-03-07 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_remove_add_gps_vehicle_registration_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_gps',
            name='Gps_device_IMEI_no',
        ),
        migrations.RemoveField(
            model_name='add_gps',
            name='install_date',
        ),
        migrations.RemoveField(
            model_name='add_gps',
            name='reminder_date',
        ),
        migrations.RemoveField(
            model_name='add_gps',
            name='renew_date',
        ),
    ]
