# Generated by Django 5.1.6 on 2025-03-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_remove_add_gps_gps_device_imei_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_gps',
            name='Gps_device_IMEI_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='add_gps',
            name='install_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='add_gps',
            name='reminder_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='add_gps',
            name='renew_date',
            field=models.DateField(null=True),
        ),
    ]
