# Generated by Django 5.1.7 on 2025-03-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_gps_details_rename_add_gps_gps_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps_master',
            name='gps_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
