# Generated by Django 5.1.6 on 2025-03-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_add_gps_gps_device_imei_no_add_gps_install_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_gps',
            name='vehicle_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
