# Generated by Django 5.1.6 on 2025-03-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_add_gps_vehicle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_gps',
            name='vehicle_id',
        ),
    ]
