# Generated by Django 5.1.7 on 2025-03-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_gps_master_gps_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_master',
            name='customer_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
