# Generated by Django 5.1.6 on 2025-03-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_remove_add_gps_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_gps',
            name='registration_no',
            field=models.IntegerField(default=987654),
            preserve_default=False,
        ),
    ]
