# Generated by Django 5.1.6 on 2025-03-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_add_gps_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_gps',
            name='registration_no',
            field=models.CharField(max_length=50),
        ),
    ]
