# Generated by Django 5.1.7 on 2025-03-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_add_gps_registration_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_gps',
            name='customer_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='add_gps',
            name='customer_phone_no',
            field=models.IntegerField(default='munindra'),
            preserve_default=False,
        ),
    ]
