# Generated by Django 5.1.7 on 2025-03-10 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_add_gps_customer_name_add_gps_customer_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_gps',
            old_name='customer_phone_no',
            new_name='customer_phone_number',
        ),
    ]
