# Generated by Django 5.1.7 on 2025-03-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_rename_customer_phone_no_add_gps_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_gps',
            name='customer_phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
