# Generated by Django 5.1.7 on 2025-03-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_rename_customer_phone_number_add_gps_customer_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_gps',
            name='customer_phone_no',
        ),
        migrations.AddField(
            model_name='add_gps',
            name='customer_phone_n',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='add_gps',
            name='ganesh',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
    ]
