# Generated by Django 5.1.7 on 2025-03-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_remove_add_gps_customer_phone_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_gps',
            old_name='customer_phone_n',
            new_name='customer_phone_no',
        ),
    ]
