# Generated by Django 5.1.7 on 2025-03-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_remove_add_gps_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_gps',
            name='customer_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='add_gps',
            name='customer_phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
