# Generated by Django 5.1.7 on 2025-03-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_add_gps_customer_name_add_gps_customer_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_gps',
            name='munindra',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
