# Generated by Django 5.1.7 on 2025-03-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_add_gps_munindra'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_gps',
            name='panan_phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
