# Generated by Django 5.1.7 on 2025-03-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_remove_add_gps_ganesh_remove_add_gps_munindra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_gps',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='add_gps',
            name='customer_phone_no',
        ),
    ]
