# Generated by Django 5.1.7 on 2025-03-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_add_gps_customer_name_add_gps_customer_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_gps',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='add_gps',
            name='customer_phone_no',
        ),
    ]
