# Generated by Django 5.1.7 on 2025-03-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_customer_master_delete_add_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('vehicle_details', models.CharField(max_length=50)),
                ('insurance_id', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=50)),
            ],
        ),
    ]
