# Generated by Django 5.1.7 on 2025-03-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_customer_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_insurance',
            name='insurance_name',
        ),
        migrations.AddField(
            model_name='add_insurance',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
