# Generated by Django 5.1.7 on 2025-03-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_remove_add_insurance_insurance_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='insurance_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('registration_no', models.CharField(max_length=50, null=True)),
                ('vehicle_model', models.DateField(null=True)),
                ('year', models.DateField(null=True)),
                ('policy_no', models.IntegerField(null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('vehicle_type', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='insurance_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('registration_no', models.CharField(max_length=50)),
                ('vehicle_model', models.DateField()),
                ('year', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Add_Insurance',
        ),
    ]
