# Generated by Django 5.1.7 on 2025-03-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_insurance_details_insurance_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance_master',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='insurance_details',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
