# Generated by Django 5.1.7 on 2025-03-11 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_insurance_master_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance_details',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='insurance_master',
            name='phone',
        ),
    ]
