# Generated by Django 5.1.7 on 2025-03-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0046_remove_insurance_details_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance_details',
            old_name='customer_id',
            new_name='insurance_id',
        ),
    ]
