# Generated by Django 5.1.7 on 2025-03-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_rename_customer_id_insurance_details_insurance_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance_master',
            old_name='customer_id',
            new_name='insurance_id',
        ),
    ]
