# Generated by Django 5.1.7 on 2025-03-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_enquiry_details_delete_add_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry_details',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
