# Generated by Django 5.1.7 on 2025-03-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0050_alter_enquiry_details_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance_details',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
