# Generated by Django 5.1.7 on 2025-03-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0051_insurance_details_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry_details',
            name='enquiry_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='insurance_master',
            name='insurance_id',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
